# Generated by Django 4.0.5 on 2022-06-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningZone_app', '0011_notificatons'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificatons',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learningZone_app.comment'),
        ),
        migrations.AlterField(
            model_name='notificatons',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learningZone_app.post'),
        ),
    ]
