# Generated by Django 4.0.4 on 2022-05-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningZone_app', '0007_post_dislike_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
